
// Objective-C API for talking to the following Go packages
//
//	github.com/FavorLabs/favorX/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __FavorX_FRAMEWORK_H__
#define __FavorX_FRAMEWORK_H__

#include "Mobile.objc.h"
#include "Universe.objc.h"

#endif
